https://www.sciencedirect.com/science/article/pii/S2211812814005318

In [92]:
# import dependencies
%matplotlib inline
#import keras
from keras.models import Sequential
from keras.activations import *
from keras.layers import *
from keras.losses import *
from keras.optimizers import *
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import talos as ta
import warnings
warnings.filterwarnings("ignore")

# suppres NumPy arrays scientific notation and round decimals to three places
np.set_printoptions(suppress=True)
np.printoptions(precision=3, suppress=True)

#libraries = [np,
#             pd,
#             sklearn,
#             keras,
#            ta]
#for library in libraries:
#    print(library, ' ', library.__version__)


requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))

for r in requirements:
    print("{}=={}".format(*r))

In [93]:
# import training data
train_data = pd.read_csv('Training_Features_and_Labels.txt', delim_whitespace=True, encoding='ISO-8859-1')
train_data.drop(columns=['Sr._No.'], inplace=True)
# import validation data
test_data = pd.read_csv('Test_Features_and_Labels.txt', delim_whitespace=True, encoding='ISO-8859-1')
test_data.drop(columns=['Sr._No.'], inplace=True)
# segregate a single row for validation
validation_data = test_data.loc[0]
test_data = test_data.iloc[1:]

In [94]:
# create NumPy arrays of training features and labels
train_features = train_data[['MRR(mm3/min)', 'Ra(µm)']].values
train_labels = train_data[['Spindle_speed(rpm)', 'Feed_rate(mm/rev)', 'Depth_of_cut(mm)']].values
print('Training Features:\n\n', train_features)
print('\nTraining Labels:\n\n', train_labels) 

Training Features:

 [[ 306.67    0.36]
 [ 609.76    0.47]
 [ 909.28    0.52]
 [ 582.94    0.8 ]
 [1158.73    0.9 ]
 [1727.36    1.1 ]
 [ 943.34    1.63]
 [1875.96    1.76]
 [2797.84    2.17]
 [ 793.04    0.38]
 [1577.02    0.48]
 [2351.92    0.54]
 [1555.25    0.81]
 [3092.37    0.82]
 [4611.35    0.97]
 [2196.85    1.92]
 [4366.5     1.91]
 [6508.93    2.03]
 [ 875.13    0.29]
 [1735.95    0.37]
 [2582.46    0.38]
 [1745.24    0.82]
 [3461.88    0.79]
 [5149.9     1.11]
 [2549.2     1.75]
 [5055.49    1.89]
 [7518.86    1.82]]

Training Labels:

 [[ 280.        0.0508    0.4   ]
 [ 280.        0.0508    0.8   ]
 [ 280.        0.0508    1.2   ]
 [ 280.        0.1016    0.4   ]
 [ 280.        0.1016    0.8   ]
 [ 280.        0.1016    1.2   ]
 [ 280.        0.1524    0.4   ]
 [ 280.        0.1524    0.8   ]
 [ 280.        0.1524    1.2   ]
 [ 710.        0.0508    0.4   ]
 [ 710.        0.0508    0.8   ]
 [ 710.        0.0508    1.2   ]
 [ 710.        0.1016    0.4   ]
 [ 710.        0

In [95]:
# create NumPy arrays of validation features and labels
test_features = test_data[['MRR(mm3/min)', 'Ra(µm)']].values
test_labels = test_data[['Spindle_speed(rpm)', 'Feed_rate(mm/rev)', 'Depth_of_cut(mm)']].values
print('Testing Features:\n\n', test_features)
print('\nTesting Labels:\n\n', test_labels)

Testing Features:

 [[2020.44    0.29]
 [6054.12    1.87]
 [5329.21    1.54]
 [5197.29    1.45]]

Testing Labels:

 [[1100.      0.05    0.69]
 [1095.      0.15    1.2 ]
 [1097.      0.13    1.14]
 [1094.      0.12    1.15]]


In [96]:
# create NumPy array for validation data
validation_features = validation_data[['MRR(mm3/min)', 'Ra(µm)']].values
validation_labels = validation_data[['Spindle_speed(rpm)', 'Feed_rate(mm/rev)', 'Depth_of_cut(mm)']].values

# reshape the validation data because it's only one row
validation_features = validation_features.reshape(1, -1)
validation_labels = validation_labels.reshape(1, -1)

print('Validation Features:\n\n', validation_features)
print('\nValidation Labels:\n\n', validation_labels)

Validation Features:

 [[1106.51    0.21]]

Validation Labels:

 [[1100.      0.05    0.4 ]]


In [97]:
# Transforms features by scaling each feature to a given range, -1 and 1 in this case
MinMax_scaler = MinMaxScaler(feature_range=(-1, 1))
train_features_MinMax = MinMax_scaler.fit_transform(train_features)
train_labels_MinMax = MinMax_scaler.fit_transform(train_labels)
test_features_MinMax = MinMax_scaler.fit_transform(test_features)
test_labels_MinMax = MinMax_scaler.fit_transform(test_labels)
validation_features_MinMax = MinMax_scaler.fit_transform(validation_features)
validation_labels_MinMax = MinMax_scaler.fit_transform(validation_labels)

#MinMax_scaler.inverse_transform(validation_labels_MinMax)

In [98]:
# Standardize features by removing the mean and scaling to unit variance
Standard_scaler = StandardScaler()
train_features_Standard = Standard_scaler.fit_transform(train_features)
train_labels_Standard = Standard_scaler.fit_transform(train_labels)
test_features_Standard = Standard_scaler.fit_transform(test_features)
test_labels_Standard = Standard_scaler.fit_transform(test_labels)
validation_features_Standard = Standard_scaler.fit_transform(validation_features)
validation_labels_Standard = Standard_scaler.fit_transform(validation_labels)

# Standard_scaler.inverse_transform(train_features_Standard)

In [99]:
p = {
    'first_neuron': [8, 12, 24],
    'second_neuron': [36, 48, 62, 84],
    'third_neuron': [36, 48, 62, 84],
    'fourth_neuron': [8, 12, 24],
    'batch_size': [10, 20, 30],
    'activation': [relu,
                   #softmax,
                   #selu,
                   #softplus,
                   #softsign,
                   #tanh,
                   #sigmoid,
                   #hard_sigmoid,
                   #exponential,
                   linear],
    'optimizer' : [#'SGD',
                   #'RMSprop',
                   #'Adagrad',
                   #'Adadelta',
                   'Adam',],
                   #'Adamax',
                   #'Nadam',],
    'loss' : [mean_squared_error,]
              #mean_absolute_error,] 
              #mean_absolute_percentage_error, 
              #mean_squared_logarithmic_error,
              #squared_hinge,hinge,
              #categorical_hinge,
              #logcosh,],
}

In [100]:
def MinMax_ann(train_features, train_labels, test_features, test_labels, params):
    
    # replace the hyperparameter inputs with references to params dictionary 
    model = Sequential()
    model.add(Dense(params['first_neuron'], input_dim=2, activation=params['activation']))
    model.add(Dense(params['second_neuron'], activation=params['activation']))
    model.add(Dense(params['third_neuron'], activation=params['activation']))
    model.add(Dense(params['fourth_neuron'], activation=params['activation']))
    model.add(Dense(3, activation='linear'))
    model.compile(loss=params['loss'], optimizer=params['optimizer'], metrics=['accuracy'])
    
    # make sure history object is returned by model.fit()
    out = model.fit(train_features_MinMax, train_labels_MinMax,
                    epochs=100,
                    batch_size=params['batch_size'],
                    verbose=0,
                    validation_data=[test_features_MinMax, test_labels_MinMax])
    
    # model output
    return out, model

In [101]:
def Standard_ann(train_features, train_labels, test_features, test_labels, params):
    
    # replace the hyperparameter inputs with references to params dictionary 
    model = Sequential()
    model.add(Dense(params['first_neuron'], input_dim=2, activation=params['activation']))
    model.add(Dense(params['second_neuron'], activation=params['activation']))
    model.add(Dense(params['third_neuron'], activation=params['activation']))
    model.add(Dense(params['fourth_neuron'], activation=params['activation']))
    model.add(Dense(3, activation='linear'))
    model.compile(loss=params['loss'], optimizer=params['optimizer'], metrics=['accuracy'])
    
    # make sure history object is returned by model.fit()
    out = model.fit(train_features_Standard, train_labels_Standard,
                    epochs=100,
                    batch_size=params['batch_size'],
                    verbose=0,
                    validation_data=[test_features_Standard, test_labels_Standard])
    
    # model output
    return out, model

In [102]:
features_MinMax = np.concatenate((train_features_MinMax, test_features_MinMax), axis=0)
labels_MinMax = np.concatenate((train_labels_MinMax, test_labels_MinMax), axis=0)

features_Standard = np.concatenate((train_features_Standard, test_features_Standard), axis=0)
labels_Standard = np.concatenate((train_labels_Standard, test_labels_Standard), axis=0)

# run the Talos experiment on MinMax data
MinMax_t = ta.Scan(features_MinMax, labels_MinMax, 
            params=p, 
            model=MinMax_ann,
            )

# run the Talos experiment on Standard data
Standard_t = ta.Scan(features_Standard, labels_Standard, 
            params=p, 
            model=Standard_ann,
            )

In [103]:
df = pd.read_csv('MinMax.csv')
df.head(3)

round_epochs  val_loss  val_acc      loss       acc  \
0           100  0.261867     0.75  0.275643  0.481481   
1           100  0.277996     1.00  0.264963  0.518519   
2           100  0.302887     0.25  0.452316  0.555556   

                              activation  batch_size  first_neuron  \
0  <function relu at 0x000001AA17107D08>          30            24   
1  <function relu at 0x000001AA17107D08>          10             8   
2  <function relu at 0x000001AA17107D08>          30            12   

   fourth_neuron                                             loss.1 optimizer  \
0              8  <function mean_squared_error at 0x000001AA170D...      Adam   
1              8  <function mean_squared_error at 0x000001AA170D...      Adam   
2              8  <function mean_squared_error at 0x000001AA170D...      Adam   

   second_neuron  third_neuron  
0             48            48  
1             36            84  
2             48            48

In [104]:
# Define the MinMax model
MinMax_model = Sequential()
MinMax_model.add(Dense(8, input_dim=2, activation='relu'))
MinMax_model.add(Dense(48, activation='relu'))
MinMax_model.add(Dense(48, activation='relu'))
MinMax_model.add(Dense(8, activation='relu'))
MinMax_model.add(Dense(3, activation='linear'))
MinMax_model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

MinMax_model.fit(train_features_MinMax,
                 train_labels_MinMax,
                 validation_data=(test_features_MinMax, test_labels_MinMax),
                 batch_size=30,
                 epochs=200)

Train on 27 samples, validate on 4 samples
Epoch 1/200
27/27 [==============================] - 1s 35ms/step - loss: 0.6807 - acc: 0.2222 - val_loss: 0.8086 - val_acc: 0.5000
Epoch 2/200
27/27 [==============================] - 0s 0us/step - loss: 0.6724 - acc: 0.2222 - val_loss: 0.7912 - val_acc: 0.5000
Epoch 3/200
27/27 [==============================] - 0s 579us/step - loss: 0.6633 - acc: 0.2222 - val_loss: 0.7727 - val_acc: 0.5000
Epoch 4/200
27/27 [==============================] - 0s 0us/step - loss: 0.6534 - acc: 0.2222 - val_loss: 0.7580 - val_acc: 0.5000
Epoch 5/200
27/27 [==============================] - 0s 579us/step - loss: 0.6449 - acc: 0.2222 - val_loss: 0.7486 - val_acc: 0.5000
Epoch 6/200
27/27 [==============================] - 0s 578us/step - loss: 0.6381 - acc: 0.2222 - val_loss: 0.7411 - val_acc: 0.5000
Epoch 7/200
27/27 [==============================] - 0s 0us/step - loss: 0.6321 - acc: 0.2593 - val_loss: 0.7345 - val_acc: 0.5000
Epoch 8/200
27/27 [==============

Epoch 63/200
27/27 [==============================] - 0s 579us/step - loss: 0.4917 - acc: 0.2963 - val_loss: 0.6015 - val_acc: 0.5000
Epoch 64/200
27/27 [==============================] - 0s 0us/step - loss: 0.4887 - acc: 0.2963 - val_loss: 0.5947 - val_acc: 0.5000
Epoch 65/200
27/27 [==============================] - 0s 0us/step - loss: 0.4856 - acc: 0.3333 - val_loss: 0.5871 - val_acc: 0.5000
Epoch 66/200
27/27 [==============================] - 0s 0us/step - loss: 0.4826 - acc: 0.3333 - val_loss: 0.5794 - val_acc: 0.5000
Epoch 67/200
27/27 [==============================] - 0s 0us/step - loss: 0.4795 - acc: 0.3333 - val_loss: 0.5717 - val_acc: 0.5000
Epoch 68/200
27/27 [==============================] - 0s 579us/step - loss: 0.4764 - acc: 0.3333 - val_loss: 0.5644 - val_acc: 0.5000
Epoch 69/200
27/27 [==============================] - 0s 0us/step - loss: 0.4732 - acc: 0.3333 - val_loss: 0.5586 - val_acc: 0.5000
Epoch 70/200
27/27 [==============================] - 0s 0us/step - loss

Epoch 125/200
27/27 [==============================] - 0s 579us/step - loss: 0.2773 - acc: 0.4815 - val_loss: 0.5023 - val_acc: 0.5000
Epoch 126/200
27/27 [==============================] - 0s 0us/step - loss: 0.2760 - acc: 0.4815 - val_loss: 0.5042 - val_acc: 0.5000
Epoch 127/200
27/27 [==============================] - 0s 0us/step - loss: 0.2748 - acc: 0.4815 - val_loss: 0.5057 - val_acc: 0.5000
Epoch 128/200
27/27 [==============================] - 0s 0us/step - loss: 0.2737 - acc: 0.4815 - val_loss: 0.5078 - val_acc: 0.5000
Epoch 129/200
27/27 [==============================] - 0s 579us/step - loss: 0.2726 - acc: 0.4815 - val_loss: 0.5107 - val_acc: 0.5000
Epoch 130/200
27/27 [==============================] - 0s 0us/step - loss: 0.2717 - acc: 0.4815 - val_loss: 0.5126 - val_acc: 0.5000
Epoch 131/200
27/27 [==============================] - 0s 0us/step - loss: 0.2707 - acc: 0.4815 - val_loss: 0.5135 - val_acc: 0.5000
Epoch 132/200
27/27 [==============================] - 0s 0us/ste

Epoch 187/200
27/27 [==============================] - 0s 0us/step - loss: 0.2378 - acc: 0.5926 - val_loss: 0.5729 - val_acc: 0.5000
Epoch 188/200
27/27 [==============================] - 0s 0us/step - loss: 0.2373 - acc: 0.5926 - val_loss: 0.5758 - val_acc: 0.5000
Epoch 189/200
27/27 [==============================] - 0s 0us/step - loss: 0.2369 - acc: 0.5926 - val_loss: 0.5781 - val_acc: 0.5000
Epoch 190/200
27/27 [==============================] - 0s 0us/step - loss: 0.2365 - acc: 0.5926 - val_loss: 0.5791 - val_acc: 0.5000
Epoch 191/200
27/27 [==============================] - 0s 0us/step - loss: 0.2360 - acc: 0.5926 - val_loss: 0.5784 - val_acc: 0.5000
Epoch 192/200
27/27 [==============================] - 0s 0us/step - loss: 0.2355 - acc: 0.5926 - val_loss: 0.5800 - val_acc: 0.5000
Epoch 193/200
27/27 [==============================] - 0s 578us/step - loss: 0.2351 - acc: 0.5926 - val_loss: 0.5813 - val_acc: 0.5000
Epoch 194/200
27/27 [==============================] - 0s 0us/step 

In [105]:
df = pd.read_csv('Standard.csv')
df.head(3)

round_epochs  val_loss  val_acc      loss       acc  \
0           100  0.386672     0.75  0.459910  0.666667   
1           100  0.466409     0.75  0.401966  0.777778   
2           100  0.511823     0.75  0.447284  0.629630   

                                activation  batch_size  first_neuron  \
0    <function relu at 0x000001AA17107D08>          30            24   
1    <function relu at 0x000001AA17107D08>          10            12   
2  <function linear at 0x000001AA17118048>          20            24   

   fourth_neuron                                             loss.1 optimizer  \
0              8  <function mean_squared_error at 0x000001AA170D...      Adam   
1              8  <function mean_squared_error at 0x000001AA170D...      Adam   
2             12  <function mean_squared_error at 0x000001AA170D...      Adam   

   second_neuron  third_neuron  
0             48            62  
1             84            84  
2             36            62

In [106]:
# Define the Standard model
Standard_model = Sequential()
Standard_model.add(Dense(24, input_dim=2, activation='relu'))
Standard_model.add(Dense(48, activation='relu'))
Standard_model.add(Dense(62, activation='relu'))
Standard_model.add(Dense(8, activation='relu'))
Standard_model.add(Dense(3, activation='linear'))
Standard_model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

Standard_model.fit(train_features_Standard,
                   train_labels_Standard,
                   validation_data=(test_features_Standard, test_labels_Standard),
                   batch_size=30,
                   epochs=200)

Train on 27 samples, validate on 4 samples
Epoch 1/200
27/27 [==============================] - 1s 36ms/step - loss: 1.0357 - acc: 0.3704 - val_loss: 0.9832 - val_acc: 0.5000
Epoch 2/200
27/27 [==============================] - 0s 579us/step - loss: 1.0190 - acc: 0.3704 - val_loss: 0.9761 - val_acc: 0.5000
Epoch 3/200
27/27 [==============================] - 0s 580us/step - loss: 0.9978 - acc: 0.1852 - val_loss: 0.9723 - val_acc: 0.2500
Epoch 4/200
27/27 [==============================] - 0s 578us/step - loss: 0.9789 - acc: 0.2593 - val_loss: 0.9712 - val_acc: 0.2500
Epoch 5/200
27/27 [==============================] - 0s 579us/step - loss: 0.9634 - acc: 0.2593 - val_loss: 0.9672 - val_acc: 0.2500
Epoch 6/200
27/27 [==============================] - 0s 578us/step - loss: 0.9487 - acc: 0.2963 - val_loss: 0.9631 - val_acc: 0.0000e+00
Epoch 7/200
27/27 [==============================] - 0s 578us/step - loss: 0.9345 - acc: 0.3333 - val_loss: 0.9594 - val_acc: 0.2500
Epoch 8/200
27/27 [====

27/27 [==============================] - 0s 0us/step - loss: 0.5601 - acc: 0.5926 - val_loss: 0.8673 - val_acc: 0.5000
Epoch 63/200
27/27 [==============================] - 0s 0us/step - loss: 0.5561 - acc: 0.5926 - val_loss: 0.8659 - val_acc: 0.5000
Epoch 64/200
27/27 [==============================] - 0s 579us/step - loss: 0.5504 - acc: 0.5556 - val_loss: 0.8625 - val_acc: 0.5000
Epoch 65/200
27/27 [==============================] - 0s 0us/step - loss: 0.5430 - acc: 0.5556 - val_loss: 0.8587 - val_acc: 0.5000
Epoch 66/200
27/27 [==============================] - 0s 578us/step - loss: 0.5349 - acc: 0.5185 - val_loss: 0.8552 - val_acc: 0.5000
Epoch 67/200
27/27 [==============================] - 0s 0us/step - loss: 0.5261 - acc: 0.5556 - val_loss: 0.8519 - val_acc: 0.5000
Epoch 68/200
27/27 [==============================] - 0s 579us/step - loss: 0.5168 - acc: 0.5556 - val_loss: 0.8483 - val_acc: 0.5000
Epoch 69/200
27/27 [==============================] - 0s 0us/step - loss: 0.5070 - 

Epoch 124/200
27/27 [==============================] - 0s 580us/step - loss: 0.3537 - acc: 0.7407 - val_loss: 0.8760 - val_acc: 0.5000
Epoch 125/200
27/27 [==============================] - 0s 0us/step - loss: 0.3528 - acc: 0.7407 - val_loss: 0.8763 - val_acc: 0.5000
Epoch 126/200
27/27 [==============================] - 0s 577us/step - loss: 0.3519 - acc: 0.7407 - val_loss: 0.8758 - val_acc: 0.5000
Epoch 127/200
27/27 [==============================] - 0s 0us/step - loss: 0.3509 - acc: 0.7407 - val_loss: 0.8763 - val_acc: 0.5000
Epoch 128/200
27/27 [==============================] - 0s 0us/step - loss: 0.3500 - acc: 0.7407 - val_loss: 0.8776 - val_acc: 0.5000
Epoch 129/200
27/27 [==============================] - 0s 0us/step - loss: 0.3491 - acc: 0.7407 - val_loss: 0.8785 - val_acc: 0.5000
Epoch 130/200
27/27 [==============================] - 0s 0us/step - loss: 0.3483 - acc: 0.7407 - val_loss: 0.8807 - val_acc: 0.5000
Epoch 131/200
27/27 [==============================] - 0s 579us/s

27/27 [==============================] - 0s 0us/step - loss: 0.3054 - acc: 0.7778 - val_loss: 0.9836 - val_acc: 0.5000
Epoch 186/200
27/27 [==============================] - 0s 578us/step - loss: 0.3046 - acc: 0.7778 - val_loss: 0.9861 - val_acc: 0.5000
Epoch 187/200
27/27 [==============================] - 0s 0us/step - loss: 0.3038 - acc: 0.7778 - val_loss: 0.9903 - val_acc: 0.5000
Epoch 188/200
27/27 [==============================] - 0s 579us/step - loss: 0.3030 - acc: 0.7778 - val_loss: 0.9948 - val_acc: 0.5000
Epoch 189/200
27/27 [==============================] - 0s 0us/step - loss: 0.3021 - acc: 0.7778 - val_loss: 0.9996 - val_acc: 0.5000
Epoch 190/200
27/27 [==============================] - 0s 579us/step - loss: 0.3012 - acc: 0.7778 - val_loss: 1.0016 - val_acc: 0.5000
Epoch 191/200
27/27 [==============================] - 0s 0us/step - loss: 0.3003 - acc: 0.7778 - val_loss: 1.0020 - val_acc: 0.5000
Epoch 192/200
27/27 [==============================] - 0s 579us/step - loss: 

In [107]:
# MinMax prediction
prediction = MinMax_model.predict(validation_features_MinMax)
prediction = MinMax_scaler.inverse_transform(prediction)
# compare
MinMax_scaler.inverse_transform(validation_labels_MinMax)
print('MinMax Prediction:\n\n', prediction)
print('\nActual:\n\n', MinMax_scaler.inverse_transform(validation_labels_MinMax))

MinMax Prediction:

 [[1100.2433      -0.0981545    0.6096643]]

Actual:

 [[1100.      0.05    0.4 ]]


In [108]:
# Standard prediction
prediction = Standard_model.predict(validation_features_Standard)
prediction = Standard_scaler.inverse_transform(prediction)
# compare
print('Standard Prediction:\n\n', prediction)
print('\nActual:\n\n', Standard_scaler.inverse_transform(validation_labels_Standard))

Standard Prediction:

 [[1100.2274        0.21553291    0.4820621 ]]

Actual:

 [[1100.      0.05    0.4 ]]
